name: cinetracker
description: "cinetracker app"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.11.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/movie.png
    - assets/popular.png
    - assets/splash.png
    - assets/upcoming.png